### ISSUE TITLE
make this non agpl

### ISSUE THREAD

**Issue by SuitespaceDev** [dotink/sage#7] opened 2022-11-01 09:22 UTC
repo is dead. let it become apache / mit / freebsd license so people can potentially revive it.

**Comment by mattsah** [comment] 2022-11-01 16:14
AGPL does not prevent others from forking this library and improving it (revival) in any way so long as they share their changes with everyone else.  It merely prevents them from closing those improvements off from the world or using it in other services/online services which are not also shared with others.

If people are interested in reviving this project, I would hope their interested enough in sharing their work and related/integraged work with others.

That said, this library is dead for a reason and "reviving it" would make likely less sense than would rewriting it.  Not only has PHP become far more advanced with new ways to introspect and therefore document code, the basic functionality that made this library usable at the time is replicable in likely a single day by simply looking at its patterns (and would be much better suited to be properly interfaced and such).  Lastly, there are far more functional templating languages that would make the output far easier to work with and transform into various formats (html, markdown, etc).

**Comment by SuitespaceDev** [comment] 2022-11-01 16:59
Welp fair enough. You're dead code, up to you. It certainty prevented us from making use.

That said AGPL is a death wish for most projects.

**Comment by mattsah** [comment] 2022-11-01 17:48
I don't know who "us" is but there are only two reasons that AGPL would have prevented your use:

1. You don't understand AGPL and have a general misconception caused by FUD which has been spread about GPL licenses more generally.
2. I intended to prevent _how_ you wanted to use it when I licensed it that way.  I hope your company does well for you, but I'm the arbiter of when I work for free.

**Closed by mattsah** 2022-11-01 17:48 UTC
